services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - TZ=Europe/Madrid    
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/config/acl_file:/mosquitto/config/acl_file:ro
      - ./mosquitto/config/password_file:/mosquitto/config/password_file:rw
      - ../certs:/mosquitto/config/certs 
    ports:
      - 1883:1883
      - 8883:8883
    restart: unless-stopped